CREATE TABLE analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  created_at TIMESTAMP NOT NULL,

  role_type VARCHAR(255),
  java_relevance VARCHAR(255),
  seniority_level VARCHAR(255),
  domain VARCHAR(255),
  vacancy_language VARCHAR(255),
  required_german_level VARCHAR(255),

  primary_stack VARCHAR(1000),
  secondary_stack VARCHAR(1000),
  nice_to_have_stack VARCHAR(1000),

  gaps VARCHAR(3000),

  job_description_preview VARCHAR(500)
);